//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MADBEntities : DbContext
    {
        public MADBEntities()
            : base("name=MADBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<tb_Account> tb_Account { get; set; }
        public virtual DbSet<tb_Menu> tb_Menu { get; set; }
        public virtual DbSet<tb_Register> tb_Register { get; set; }
        public virtual DbSet<tb_Role_Permission> tb_Role_Permission { get; set; }
        public virtual DbSet<tb_Role_Prsn_Detail> tb_Role_Prsn_Detail { get; set; }
        public virtual DbSet<tb_LblCaption> tb_LblCaption { get; set; }
        public virtual DbSet<tb_User> tb_User { get; set; }
        public virtual DbSet<tb_ResponeMessage> tb_ResponeMessage { get; set; }
        public virtual DbSet<tb_Brand> tb_Brand { get; set; }
        public virtual DbSet<tb_Category> tb_Category { get; set; }
        public virtual DbSet<tb_Product> tb_Product { get; set; }
        public virtual DbSet<tb_File> tb_File { get; set; }
    
        public virtual ObjectResult<string> pm_GetMessage(string msg_id, string lang_code)
        {
            var msg_idParameter = msg_id != null ?
                new ObjectParameter("msg_id", msg_id) :
                new ObjectParameter("msg_id", typeof(string));
    
            var lang_codeParameter = lang_code != null ?
                new ObjectParameter("lang_code", lang_code) :
                new ObjectParameter("lang_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("pm_GetMessage", msg_idParameter, lang_codeParameter);
        }
    
        public virtual int pm_AppFirstLog(string uSERID, string nEW_PWD)
        {
            var uSERIDParameter = uSERID != null ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(string));
    
            var nEW_PWDParameter = nEW_PWD != null ?
                new ObjectParameter("NEW_PWD", nEW_PWD) :
                new ObjectParameter("NEW_PWD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pm_AppFirstLog", uSERIDParameter, nEW_PWDParameter);
        }
    }
}
