//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Account
    {
        public string REG_ID { get; set; }
        public string ACCOUNT_ID { get; set; }
        public Nullable<int> ACC_TYPE { get; set; }
    }
}
