//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_File
    {
        public string FILE_ID { get; set; }
        public string ITEM_ID { get; set; }
        public string FILE_TYPE { get; set; }
        public string FILE_NAME { get; set; }
        public string FILE_EXTENSION { get; set; }
        public string FILE_PATH { get; set; }
    }
}
