//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Menu
    {
        public int MENU_ID { get; set; }
        public string MENU_CAPTION { get; set; }
        public Nullable<int> MENU_PARENTS_KEY { get; set; }
        public Nullable<int> MENU_ORDER { get; set; }
        public string ACTION { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string LANGUAGE_CODE { get; set; }
    }
}
