//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Role_Prsn_Detail
    {
        public int RA_ID { get; set; }
        public int RP_ID { get; set; }
        public string ROLE_NAME { get; set; }
    
        public virtual tb_Role_Permission tb_Role_Permission { get; set; }
    }
}
