//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_User
    {
        public string USER_ID { get; set; }
        public string USER_CODE { get; set; }
        public string USER_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<bool> IS_FIRST_LOG { get; set; }
        public Nullable<int> ROLE_ID { get; set; }
        public Nullable<System.DateTime> CREATE_AT { get; set; }
        public string CREATE_BY { get; set; }
        public string PWD { get; set; }
    }
}
